name: Publish 1.20.1 To GitHub Repository

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3.5.3
      - name: Set up JDK 17
        uses: actions/setup-java@v3.11.0
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Inject Commit Revision
        run: "echo \"-${GITHUB_SHA::8}\" >> git_reference_id.txt"

      - name: Generate 1.20.1 data
        run: sudo gradle clean cleanAllMinecraft generateData_1.20.1

      - name: Push 1.20.1 Data
        uses: cpina/github-action-push-to-another-repository@v1.7.2
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source-directory: "ArticData/1.20.1/"
          user-email: "articdata@bot.io"
          destination-github-username: "Articdive"
          destination-repository-name: "ArticData"
          target-branch: "1.20.1"